spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.212:3306/jpa
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      update更新或者创建数据表结构
      ddl-auto: update
#      控制台显示sql
    show-sql: true
